name: Build Docker Image

on:
  push:
    tags:
      - '**'

env:
  IMAGE_NAME: klastic/xmage-beta

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker/alpine_openjdk8_from_beta
          push: true
          tags: ${{env.IMAGE_NAME}}:latest, ${{env.IMAGE_NAME}}:alpine, ${{env.IMAGE_NAME}}:openjdk8, ${{env.IMAGE_NAME}}:${{ env.TAG }}

      - name: Redeploy Docker Stack via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SWARM_MANAGER }}
          username: ${{ secrets.SWARM_USER }}
          key: ${{ secrets.SWARM_KEY }}
          port: ${{ secrets.SWARM_PORT }}
          script: |
            git clone https://github.com/LostKode/docker-swarm-configs.git /tmp/repo
            
            cd /tmp/repo/
            
            docker stack deploy --compose-file xmage.yml xmage --with-registry-auth
            
            rm -rf /tmp/repo
